[project]
name = "backend"
version = "0.1.0"
description = "This is the backend for the cyoa project."
readme = "README.md"
requires-python = ">=3.11"

[tool.uv.workspace]
members = ["story_service", "server"]
