# fly.toml app configuration file generated for story-service-muddy-glitter-511 on 2024-11-16T18:15:46+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'story-service'
primary_region = 'sin'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 9080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[http_service.ports]]
  handlers = ["http"]
  port = 80
  force_https = true

[[http_service.ports]]
  handlers = ["tls", "http"]
  port = 443

[http_service.tls_options]
  alpn = ["h2", "http/1.1"]

[vm]
  cpu_kind = "shared"
  cpu_cores = 2
  memory_mb = 2048
