name: Build

on:
  push:
    branches:
      - "*" # Run on all branches

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: frontend

      - name: Type Check
        run: npm run type-check
        working-directory: frontend

      - name: Build project
        run: npm run build
        working-directory: frontend

      - name: Check build success
        run: echo "Build completed successfully" # Just check if the build runs without errors
